name: Build & Auto-Release Signed APKs (notes/mental/journal)

on:
  # Build only when a tag like v2.15.1 (or v123) is pushed, or run manually
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { flavor: [notes, mental, journal] }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Recreate PKCS12 keystore from secret
        env: { ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} }
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > $HOME/embanaphe.p12
          echo "ANDROID_KEYSTORE_PATH=$HOME/embanaphe.p12" >> $GITHUB_ENV

      - run: chmod +x ./gradlew

      - name: Assemble ${{ matrix.flavor }}Release (signed)
        env:
          ANDROID_KEYSTORE_PATH: ${{ env.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: ./gradlew assemble${{ matrix.flavor^ }}Release

      - uses: actions/upload-artifact@v4
        with:
          name: markor-${{ matrix.flavor }}-release-signed
          path: app/build/outputs/apk/${{ matrix.flavor }}/release/*.apk
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist }

      - name: List artifacts
        run: find dist -type f -maxdepth 3 -print

      - name: Create GitHub Release (reusing pushed tag)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Upstream sync: ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            dist/markor-notes-release-signed/*.apk
            dist/markor-mental-release-signed/*.apk
            dist/markor-journal-release-signed/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
