name: Build & Auto-Release Signed APKs (Markor forks)

on:
  push:
    tags: [ 'v*' ]   # only run when a tag like v2.15.1 is pushed
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { flavor: notes,     cap: Notes     }
          - { flavor: mental,    cap: Mental    }
          - { flavor: journal,   cap: Journal   }
          - { flavor: tabletop,  cap: Tabletop  }
          - { flavor: dev,       cap: Dev       }
          - { flavor: health,    cap: Health    }
          - { flavor: wiki,      cap: Wiki      }
          - { flavor: social,    cap: Social    }
          - { flavor: reference, cap: Reference }
          - { flavor: learn,     cap: Learn     }
          - { flavor: todo,      cap: Todo      }
          - { flavor: scratch,   cap: Scratch   }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Recreate PKCS12 keystore from secret
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$HOME/embanaphe.p12"
          echo "ANDROID_KEYSTORE_PATH=$HOME/embanaphe.p12" >> "$GITHUB_ENV"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Assemble ${{ matrix.flavor }}Release (signed)
        env:
          ANDROID_KEYSTORE_PATH: ${{ env.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: ./gradlew assemble${{ matrix.cap }}Release

      - name: Rename APK
        run: |
          mkdir -p rename/${{ matrix.flavor }}
          SRC=$(ls app/build/outputs/apk/${{ matrix.flavor }}/release/*.apk | head -n 1)
          DEST=rename/${{ matrix.flavor }}/markor-${{ matrix.flavor }}.apk
          cp "$SRC" "$DEST"
          echo "Renamed $SRC → $DEST"

      - name: Upload ${{ matrix.flavor }} signed APK
        uses: actions/upload-artifact@v4
        with:
          name: markor-${{ matrix.flavor }}-release-signed
          path: rename/${{ matrix.flavor }}/markor-${{ matrix.flavor }}.apk
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: List files (debug)
        run: find dist -type f -maxdepth 3 -print
      - name: Create GitHub Release and upload APKs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Upstream sync: ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: dist/**/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
