name: Sync Upstream Markor

on:
  schedule:
    - cron: "0 2 * * *"   # every day at 2 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/gsantner/markor.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
